version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:mysql://localhost:3306/cukrarna?user=root?password=

  db:
    image: "mysql:10.7"
    environment:
      - MYSQL_DATABASE=cukrarna
    ports:
      - "3306:3306"